### ISSUE TITLE
[Feature Request] Publish Plugin

### ISSUE THREAD

**Issue by vinkla** [alexmacarthur/picperf-wordpress#1]
Please publish the plugin on either wordpress.org or packagist.org so that it can be installed using Composer.

```sh
composer require wpackagist-plugin/picperf # wordpress.org

composer require alexmacarthur/picperf # packagist.org
```

**Comment by alexmacarthur** [comment]
Done! Thanks for the call-out. It lives here: 

https://packagist.org/packages/alexmacarthur/picperf

I'll update the documentation so people know this option exists.

**Comment by alexmacarthur** [comment]
Done! Thanks for the call-out. It lives here: 

https://packagist.org/packages/picperf/wordpress

I'll update the documentation so people know this option exists.
